spring:
  application:
    name: core
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticketing}
    username: ${DB_USERNAME:ticketing}
    password: ${DB_PASSWORD:ticketing}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

identity:
  jwt:
    private-key: ${IDENTITY_JWT_PRIVATE_KEY:}
    public-key: ${IDENTITY_JWT_PUBLIC_KEY:}
    issuer: ${IDENTITY_JWT_ISSUER:}
    audience: ${IDENTITY_JWT_AUDIENCE:}
